### ISSUE TITLE
Insufficient number of peers

### ISSUE THREAD

**Issue by defector85** [mafintosh/peerflix#268]
Hello.
Would it be possible to ask for more peers via terminal, please?
I've encountered this issue many times.
If I download the same torrent via Deluge, it goes all the way up to my max DL speed, but streaming the exact same torrent via peerflix, it doesn't reach the same speed.

Thanks in advance,
Sorry for my bad english,
Dimitris

**Comment by jaruba** [comment]
Try setting the maximum number of simultaneous connections

```
peerflix magnet-link --connections 200
```

Default should be `100`

**Comment by defector85** [comment]
Thanks for the reply, jaruba.

Will try that.

**Comment by jaruba** [comment]
Please remember to close the issue if you think it is solved.

Also, be mindful of setting too many maximum simultaneous connections because if your on wifi, there is a limit to the number of connections that you can use and if you reach that limit, all new connections will be stopped. So the browser will stop loading new pages, etc. This is the definition of network flooding.

**Comment by defector85** [comment]
Yeah, I have tried 2-3 torrents, and it seems that your solution works.
I'm on Ethernet, so I think I'm ok, but besides that, when I choose to stream a torrent, I don't usually surf the net.
Thanks so much for your help!

**Comment by Sohaib175** [comment]
> Thanks for the reply, jaruba.
> 
> Will try that.
> 
> update: It seems that jaruba's "solution" works! Thanks a lot.

Can u please explain me hoe to increase the magnet links connections
