### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by naholyr** [mafintosh/peerflix#270]
Is it simply paused? Or does the author have no possibility to keep maintaining it?

No merged or commented PR since months (years?), this project deserves some love ;)

**Comment by jaruba** [comment]
It's def not my place to answer this question, but `peerflix` itself is not the entire project (although it was made to work standalone too), it's a wrapper for `torrent-stream` (that creates streaming links for each file in the downloading torrent, and much more), that is itself split into a lot of other modules.

The dependencies of `peerflix` are still evolving, slowly ofc as this is a mature project. For example, the fact that `torrent-stream` and `webtorrent` now use the same peer discovery module.

`peerflix` has very few ways that it can still progress, all of which can be considered a low priority, as it already goes above and beyond a simple streaming server.

The natural progression of it would be to make a wrapper for `peerflix`, which should obviously be a player. Which is what @mafintosh (with [Playback](https://github.com/mafintosh/playback)), me (with [Powder Player](https://github.com/jaruba/PowderPlayer)) and many many others are doing now.

All the apps (I say "all" because there are a lot more then you could possibly imagine) are the natural evolution of `peerflix` as they give a lot more possibilities of progression then `peerflix` in the terminal could, like offering a user friendly GUI for it and the possibility of media playback without needing an additional app installed too.

**Comment by Ivshti** [comment]
I'd like to add something.

`peerflix` and `torrent-stream` are practically perfect as a tech. They almost have nothing to improve.

They do one simple thing: stream interface from BitTorrent (`torrent-stream`) and HTTP server on top (`peerflix`).

Next progressions, which are separate things:
1) as @jaruba said, players
2) more technological though, [hyperdrive](http://github.com/mafintosh/hyperdrive) and ipfs; both go further than the BitTorrent protocol, to solve the problem of files (yes, files in general) through peer to peer
3) less interesting IMHO, efforts to tune the BitTorrent protocol for live streaming; this should be simple with an extension of the protocol, and plain old HLS :)

**Comment by naholyr** [comment]
I fully understand this type of evolution, however peerflix itself has 65 open issues and 13 open PR with almost no feedback, and no relevant commit for more than a year now.

It's far from being *perfect* as the subject of players as you said is totally open, there are obviously bugs (or there would not be any open issue, or they would all have been tagged as "nofix" and closed) so maintenance is required, but anyone who would like to contribute will just see an unmaintained project with no chance of PR being actually merged. That was more the sense of my question: is the project still maintained?

**Comment by Ivshti** [comment]
OK, regarding your exact question @naholyr: you have to tag @mafintosh for that :) 

My guess would be that he doesn't consider the project un-maintained, but simply on the back burner.

Maybe a new person should be given maintainer privileges to sort the PRs out :) E.g. @feross now maintains a few of mafintosh's packages

**Comment by mafintosh** [comment]
This is project is still very much active (i use it daily as well). Most issues are just people experiencing an error because of some weird network issue they might have. On the technical side there isn't really that much more to be done other than minor tweaks here and there. 

If any one wants to step up and help comment and close issues or merge/close PRs that would (as always) be greatly appreciated. Special thanks to @Ivshti @jaruba and others for already helping out :)
