### ISSUE TITLE
Peerflix does not stop when VLC Close

### ISSUE THREAD

**Issue by webkitten** [mafintosh/peerflix#271]
I'm using win7, peerflix continue download when vlc close (sorry, my Eng is not well)

**Comment by jaruba** [comment]
Well.. yeah, but it's not designed too.

The way your using it now, is that your starting peerflix as a child process, and then peerflix starts VLC as a child process, when you close VLC it's process dies, but the peerflix child process is still active, unless you close that too, it will continue to be active.

**Comment by jaruba** [comment]
The solution to this is to not start peerflix in a child process, as explained in https://github.com/mafintosh/peerflix/issues/272 . Considering that you'll start VLC as a child process yourself instead of peerflix, you can listen to it's events to figure out when it's closing and also close peerflix programatically along with it.

**Comment by webkitten** [comment]
thanks for response! I opened this issue because I thought that argument --no-quit when i start peerflix from cmd needs for do the opposite, but i tried this on 'clean' virtual machine and i saw the same(peerflix continue download). Is it normal or bug?)
