### ISSUE TITLE
Glitchy stream even after the movie was fully loaded.

### ISSUE THREAD

**Issue by hThoreau** [mafintosh/peerflix#325]
Good night,

I'm running in a Debian Jessie, having installed peerflix using [this method](http://www.webupd8.org/2014/03/peerflix-stream-torrents-with-vlc-or.html). For my first try, I selected the most ranked torrent available for the movie "Inception". The stream's image was both [laggy and glitched](http://imgur.com/a/X0m5H), and I waited to see if the problem would eventually be resolved by having more parts of the video loaded. Eventually the file was fully downloaded and could even be watched fully and without any problems using the video file available in the _tmp_ folder, but the stream continued with no improvements on quality.

How could I repair this?

**Comment by mafintosh** [comment]
Please don't link/discuss copyrighted material here.

**Comment by hThoreau** [comment]
I'm sorry, I didn't consider the copyright matter for what I intended to be just a test. It was just the first movie that popped into my mind, but I see your point. I'm going to edit the original post and use an example already in the public domain, could you kindly reopen the issue then?

Thank you.

**Comment by jaruba** [comment]
This is a VLC issue (two VLC issues actually, but one in particular causes the other too), not a peerflix issue. I know of it and have debugged it in the past.

An easy way to reproduce this bug is by seeking forward then backward on a stream. VLC will start buffering constantly with very small pauses between the buffering phases. (even if the video is 100% downloaded)

The reason for this is that VLC keeps requesting the same stream parts over and over frantically, thus flooding the peerflix server with requests.
